*NumPy*

1) NumPy is a Python library
2) it is used for working with arrays
3) It is short for "Numerical python"
4) It is used for computation and processing of single and multi-dimensional array of elments
5) Similar memory consumption and better runtime behavior 

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a.ndim #Dimension of the array

1

In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
b.shape

(2, 3)

In [4]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Accessing and CHnaging specific elements , rows and columns

In [7]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
a.ndim

2

In [9]:
a.shape

(2, 7)

In [10]:
a[0,3]

np.int64(4)

In [ ]:
a[0,:] #Print specific row

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
a[:,0] #print specific column

array([1, 8])

In [13]:
a[0,3] = 40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
a[0,4]=50
print(a)

[[ 1  2  3 40 50  6  7]
 [ 8  9 10 11 12 13 14]]


Zeros/Ones method in NumPy

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.full((3,3), 5) #Create a 3x3 array filled with 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [18]:
np.random.rand(4,4)

array([[0.3092426 , 0.37394366, 0.08299686, 0.51480648],
       [0.5536169 , 0.5466787 , 0.03007162, 0.79108246],
       [0.15152247, 0.93005544, 0.79217789, 0.02753234],
       [0.77598895, 0.45838769, 0.34854185, 0.5448141 ]])

In [20]:
np.random.randint(-4,1, size=(3,3)) #Create a 3x3 array with random values between -4 and 1

array([[-4, -2, -1],
       [-2, -4, -2],
       [-3, -4, -4]], dtype=int32)

In [21]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Practice Questions

Extract all the first 3 rows of the last 5 columns in a given numpy 2D aeear 'a'

In [25]:
a1 = np.array([[1,2,3,4,5,6],
              [10,20,30,40,50,60],
              [12,12,12,12,12,12],
              [11,21,31,41,51,61],
              [13,24,34,54,44,64]])

In [28]:
a1[:3,-5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

In [30]:
#2 
n=5
z = np.zeros((n,n))
z[n//2, :]=1
z[:,n//2]=1
print(z)

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
